####################################################################
# This configuration is adapted from Damien Zufferey's PSync project
#            https://github.com/dzufferey/psync
####################################################################
os:
  - linux

language: scala

sudo: true

scala:
  - 2.12.6

jdk:
  - openjdk8

dist: trusty
  
before_install:
  - sudo apt-get -qq install lib32stdc++6

notifications:
  email: false

install:
  - ./.ci/install_z3.sh

env:
  - PATH="$HOME/z3/z3-4.7.1-x64-ubuntu-14.04/bin/:$PATH"

before_script:
  - sudo chmod +x /usr/local/bin/sbt

script:
#  - sbt ++$TRAVIS_SCALA_VERSION test assembly
  - sbt ++$TRAVIS_SCALA_VERSION assembly

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/z3
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

