# Full creusot install with opam and why3-ide
# Roughly 25% larger than the default image
FROM ubuntu:jammy

RUN \
  apt-get update && \
  apt-get install opam autoconf -y && \
  apt-get install -y --no-install-recommends z3 && \
  # Required for `why3-ide`
  apt-get install libcairo2-dev libexpat1-dev libgtk-3-dev libgtksourceview-3.0-dev -y && \
  # Required for Rust
  apt-get install curl build-essential libssl-dev pkg-config -y && \
  rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash cuser
USER cuser
WORKDIR /home/cuser

RUN opam init --disable-sandboxing
ENV PATH=/home/cuser/.opam/default/bin:$PATH

# No idea why the latest version doesn't work!
RUN opam pin add --yes why3 https://gitlab.inria.fr/why3/why3.git#8641e4ae51c26e3aa1ee381afd8e9551e9483790
RUN opam install --yes ocamlgraph why3
RUN opam pin add --yes why3-ide https://gitlab.inria.fr/why3/why3.git#8641e4ae51c26e3aa1ee381afd8e9551e9483790
RUN opam install --yes lablgtk3 lablgtk3-sourceview3 why3-ide
RUN why3 config detect
# Not needed
# RUN sed -i 's/4.8.12/4.8.10/' /home/cuser/.why3.conf

# Install rust
ENV PATH=/home/cuser/.cargo/bin:$PATH
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain none

# Download creusot
RUN git clone https://github.com/xldenis/creusot.git /home/cuser/creusot
WORKDIR /home/cuser/creusot

# Build creusot
ENV CARGO_INCREMENTAL=false
RUN cargo fetch
RUN cargo build
RUN cargo test

COPY prove prove

ENTRYPOINT ["bash"]
